server {
    listen 80;
    server_name kamcofarm.com www.kamcofarm.com;
    # Redirection forcée vers HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name kamcofarm.com www.kamcofarm.com;

    client_max_body_size 20M;

    ssl_certificate /etc/letsencrypt/live/kamcofarm.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kamcofarm.com/privkey.pem;

    # Frontend (Landing page)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Custom Dashboard
    location ^~ /admin/ {
        alias /usr/share/nginx/html/dashboard/;
        index index.html;
        try_files $uri $uri/ /admin/index.html;
    }

    # Django API 
    location ~ ^/api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Django Administration standard 
    location ~ ^/django-admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }
}
