# Generated by Django 6.0.1 on 2026-03-26 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0003_produitagricole_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonneNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5)),
                ('est_actif', models.BooleanField(default=True)),
                ('est_verifie', models.BooleanField(default=False)),
                ('token_verification', models.CharField(blank=True, max_length=64, null=True)),
                ('token_desinscription', models.CharField(blank=True, max_length=64, null=True)),
                ('source', models.CharField(blank=True, help_text="D'où vient cet abonné", max_length=100, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_desinscription', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Abonné newsletter',
                'verbose_name_plural': 'Abonnés newsletter',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='SourceLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Source de lead',
                'verbose_name_plural': 'Sources de leads',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CampagneMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_campagne', models.CharField(choices=[('EMAIL', 'Campagne email'), ('RESEAUX_SOCIAUX', 'Réseaux sociaux'), ('SALON', 'Salon / Foire'), ('PUBLICITE', 'Publicité'), ('PARRAINAGE', 'Parrainage'), ('CONTENU', 'Marketing de contenu'), ('SMS', 'Campagne SMS'), ('AUTRE', 'Autre')], max_length=20)),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée'), ('EN_PAUSE', 'En pause')], default='PLANIFIEE', max_length=15)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('budget_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_depense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('objectif', models.TextField(blank=True, null=True)),
                ('public_cible', models.TextField(blank=True, null=True)),
                ('leads_generes', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clics', models.PositiveIntegerField(default=0)),
                ('taux_conversion', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('roi', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campagne marketing',
                'verbose_name_plural': 'Campagnes marketing',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('poste', models.CharField(blank=True, max_length=200, null=True)),
                ('pays', models.CharField(default='Cameroun', max_length=100)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('CONTACTE', 'Contacté'), ('QUALIFIE', 'Qualifié'), ('PROPOSITION', 'Proposition envoyée'), ('NEGOCIATION', 'En négociation'), ('CONVERTI', 'Converti en client'), ('PERDU', 'Perdu')], default='NOUVEAU', max_length=15)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='MOYENNE', max_length=10)),
                ('produits_interesses', models.TextField(blank=True, help_text='Produits qui intéressent ce prospect', null=True)),
                ('budget_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('volume_estime_tonnes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_dernier_contact', models.DateTimeField(blank=True, null=True)),
                ('date_prochain_contact', models.DateTimeField(blank=True, null=True)),
                ('date_conversion', models.DateTimeField(blank=True, null=True)),
                ('raison_perte', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_assignes', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_crees', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='marketing.sourcelead')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='InteractionLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_interaction', models.CharField(choices=[('APPEL', 'Appel téléphonique'), ('EMAIL', 'Email'), ('REUNION', 'Réunion'), ('WHATSAPP', 'WhatsApp'), ('VISITE', 'Visite terrain'), ('SALON', 'Salon / Événement'), ('AUTRE', 'Autre')], max_length=15)),
                ('sujet', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resultat', models.TextField(blank=True, null=True)),
                ('date_interaction', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('effectuee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions_leads', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='marketing.lead')),
            ],
            options={
                'verbose_name': 'Interaction lead',
                'verbose_name_plural': 'Interactions leads',
                'ordering': ['-date_interaction'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_fr', models.CharField(max_length=255)),
                ('titre_en', models.CharField(blank=True, max_length=255, null=True)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField(blank=True, null=True)),
                ('type_promotion', models.CharField(choices=[('POURCENTAGE', 'Réduction en pourcentage'), ('MONTANT_FIXE', 'Réduction montant fixe'), ('LIVRAISON', 'Livraison gratuite'), ('PACK', 'Offre pack')], default='POURCENTAGE', max_length=15)),
                ('valeur_reduction', models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage ou montant selon le type', max_digits=10)),
                ('code_promo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tous_produits', models.BooleanField(default=False, help_text='Applicable à tous les produits')),
                ('montant_minimum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantite_minimum_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usage_maximum', models.PositiveIntegerField(default=0, help_text='0 = illimité')),
                ('usage_actuel', models.PositiveIntegerField(default=0)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('est_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketing/promotions/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('creee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_creees', to=settings.AUTH_USER_MODEL)),
                ('produits', models.ManyToManyField(blank=True, related_name='promotions', to='produits.produitagricole')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-date_debut'],
            },
        ),
    ]
