# Generated by Django 6.0.1 on 2026-04-07 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=255)),
                ('client_entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('type_evaluation', models.CharField(choices=[('PRODUIT', 'Qualité des produits'), ('SERVICE', 'Qualité du service'), ('AGENT', 'Qualité des agents'), ('LIVRAISON', 'Qualité de la livraison'), ('LOCATION', 'Qualité de la location'), ('GENERAL', 'Satisfaction générale')], default='GENERAL', max_length=20)),
                ('satisfaction_produit', models.PositiveSmallIntegerField(choices=[(1, '⭐ Moins satisfaisant'), (2, '⭐⭐ Moyen'), (3, '⭐⭐⭐ Satisfaisant'), (4, '⭐⭐⭐⭐ Bon'), (5, '⭐⭐⭐⭐⭐ Très bon')], default=3, help_text='Satisfaction qualité produits')),
                ('satisfaction_service', models.PositiveSmallIntegerField(choices=[(1, '⭐ Moins satisfaisant'), (2, '⭐⭐ Moyen'), (3, '⭐⭐⭐ Satisfaisant'), (4, '⭐⭐⭐⭐ Bon'), (5, '⭐⭐⭐⭐⭐ Très bon')], default=3, help_text='Satisfaction qualité service')),
                ('satisfaction_agent', models.PositiveSmallIntegerField(choices=[(1, '⭐ Moins satisfaisant'), (2, '⭐⭐ Moyen'), (3, '⭐⭐⭐ Satisfaisant'), (4, '⭐⭐⭐⭐ Bon'), (5, '⭐⭐⭐⭐⭐ Très bon')], default=3, help_text='Satisfaction qualité agents')),
                ('satisfaction_globale', models.PositiveSmallIntegerField(choices=[(1, '⭐ Moins satisfaisant'), (2, '⭐⭐ Moyen'), (3, '⭐⭐⭐ Satisfaisant'), (4, '⭐⭐⭐⭐ Bon'), (5, '⭐⭐⭐⭐⭐ Très bon')], default=3, help_text='Satisfaction globale')),
                ('notes', models.TextField(blank=True, help_text='Impressions et commentaires du client', null=True)),
                ('points_positifs', models.TextField(blank=True, null=True)),
                ('points_ameliorer', models.TextField(blank=True, null=True)),
                ('recommande', models.BooleanField(default=True, help_text='Le client recommande-t-il nos services ?')),
                ('canal', models.CharField(choices=[('TELEPHONE', 'Appel téléphonique'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('VISITE', 'Visite en personne'), ('FORMULAIRE', 'Formulaire en ligne'), ('AUTRE', 'Autre')], default='TELEPHONE', max_length=20)),
                ('date_evaluation', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_sav', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Évaluation SAV',
                'verbose_name_plural': 'Évaluations SAV',
                'ordering': ['-date_evaluation'],
            },
        ),
    ]
