# Generated by Django 6.0.1 on 2026-04-07 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_evaluationsav'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConverti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('pays', models.CharField(default='Cameroun', max_length=100)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('origine', models.CharField(choices=[('LEAD', 'Depuis un lead converti'), ('COMMANDE', 'Depuis une commande'), ('LOCATION', 'Depuis une location'), ('MANUEL', 'Ajouté manuellement')], default='COMMANDE', max_length=10)),
                ('nb_achats', models.PositiveIntegerField(default=0)),
                ('total_achats', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('nb_locations', models.PositiveIntegerField(default=0)),
                ('total_locations', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('nb_operations_total', models.PositiveIntegerField(default=0)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('eligible_promotion', models.BooleanField(default=False)),
                ('raison_eligibilite', models.TextField(blank=True, null=True)),
                ('promotion_proposee', models.BooleanField(default=False)),
                ('date_derniere_promotion', models.DateField(blank=True, null=True)),
                ('derniere_note_satisfaction', models.PositiveSmallIntegerField(blank=True, help_text='Dernière note de satisfaction (1-5)', null=True)),
                ('moyenne_satisfaction', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('nb_evaluations', models.PositiveIntegerField(default=0)),
                ('notes_sav', models.TextField(blank=True, null=True)),
                ('date_premiere_operation', models.DateField(blank=True, null=True)),
                ('date_derniere_operation', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('lead_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_converti', to='marketing.lead')),
            ],
            options={
                'verbose_name': 'Client converti',
                'verbose_name_plural': 'Clients convertis',
                'ordering': ['-montant_total'],
            },
        ),
    ]
