# Generated by Django 6.0.1 on 2026-03-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_fr', models.CharField(max_length=200)),
                ('titre_en', models.CharField(blank=True, max_length=200, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('categorie', models.CharField(choices=[('PLANTATION', 'Plantation'), ('RECOLTE', 'Récolte'), ('CONDITIONNEMENT', 'Conditionnement'), ('EXPORT', 'Export & Logistique'), ('EQUIPE', 'Notre Équipe'), ('PRODUITS', 'Produits'), ('EVENEMENT', 'Événement'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('emoji', models.CharField(blank=True, help_text='Emoji représentant la catégorie (ex: 🍍, 🥭, 📦)', max_length=10, null=True)),
                ('est_visible', models.BooleanField(default=True, help_text='Afficher cette photo sur le site public')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier)")),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Photo Galerie',
                'verbose_name_plural': 'Photos Galerie',
                'ordering': ['ordre', '-date_ajout'],
            },
        ),
    ]
