# Generated by Django 6.0.1 on 2026-03-24 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0003_produitagricole_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('contact_nom', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(default='Cameroun', max_length=100)),
                ('type_fournisseur', models.CharField(choices=[('LOCAL', 'Fournisseur Local'), ('INTERNATIONAL', 'Fournisseur International')], default='LOCAL', max_length=20)),
                ('produits_fournis', models.TextField(blank=True, help_text='Description des produits fournis', null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('client_nom', models.CharField(max_length=200)),
                ('client_entreprise', models.CharField(blank=True, max_length=200, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('destination', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('EN_PREPARATION', 'En préparation'), ('EXPEDIEE', 'Expédiée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('date_livraison_effective', models.DateField(blank=True, null=True)),
                ('creee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande Client',
                'verbose_name_plural': 'Commandes Clients',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYEE', 'Envoyée au fournisseur'), ('CONFIRMEE', 'Confirmée'), ('RECUE', 'Marchandise reçue'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('creee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_fournisseur_creees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='supplychain.fournisseur')),
            ],
            options={
                'verbose_name': 'Commande Fournisseur',
                'verbose_name_plural': 'Commandes Fournisseurs',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='supplychain.commandeclient')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commandes', to='produits.produitagricole')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='LigneCommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='supplychain.commandefournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_achats', to='produits.produitagricole')),
            ],
            options={
                'verbose_name': "Ligne d'achat fournisseur",
                'verbose_name_plural': "Lignes d'achat fournisseur",
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tracking', models.CharField(blank=True, max_length=100, null=True)),
                ('transporteur', models.CharField(blank=True, max_length=200, null=True)),
                ('mode_transport', models.CharField(choices=[('ROUTIER', 'Transport routier'), ('MARITIME', 'Transport maritime'), ('AERIEN', 'Transport aérien'), ('FERROVIAIRE', 'Transport ferroviaire')], default='ROUTIER', max_length=20)),
                ('adresse_depart', models.CharField(default='Douala, Cameroun', max_length=255)),
                ('adresse_arrivee', models.CharField(max_length=255)),
                ('poids_total_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cout_transport', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_TRANSIT', 'En transit'), ('LIVREE', 'Livrée'), ('RETOUR', 'Retour'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20)),
                ('date_expedition', models.DateField(blank=True, null=True)),
                ('date_livraison_estimee', models.DateField(blank=True, null=True)),
                ('date_livraison_effective', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='supplychain.commandeclient')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée de stock'), ('SORTIE', 'Sortie de stock'), ('AJUSTEMENT', 'Ajustement'), ('PERTE', 'Perte / Déchet')], max_length=20)),
                ('quantite_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif', models.TextField(blank=True, null=True)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('commande_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='supplychain.commandeclient')),
                ('commande_fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='supplychain.commandefournisseur')),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to='produits.produitagricole')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
