# Generated by Django 6.0.1 on 2026-04-13 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0002_reglealerteiot_capteuriot_donneestelemetrie_and_more'),
        ('produits', '0003_produitagricole_image_and_more'),
        ('supplychain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignecommandeclient',
            options={},
        ),
        migrations.AddField(
            model_name='lignecommandeclient',
            name='categorie_ligne',
            field=models.CharField(choices=[('PRODUIT_AGRICOLE', 'Produit agricole'), ('MATERIEL', 'Matériel / Équipement'), ('SERVICE', 'Prestation de service'), ('AUTRE', 'Autre')], default='PRODUIT_AGRICOLE', max_length=20),
        ),
        migrations.AddField(
            model_name='lignecommandeclient',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lignecommandeclient',
            name='equipement',
            field=models.ForeignKey(blank=True, help_text='Équipement si vente de matériel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commandes', to='equipements.equipement'),
        ),
        migrations.AlterField(
            model_name='lignecommandeclient',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commandes', to='produits.produitagricole'),
        ),
    ]
