# Generated by Django 6.0.6 on 2026-06-09 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0002_alter_lignecommandeclient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('client_nom', models.CharField(max_length=255)),
                ('client_entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('client_adresse', models.TextField(blank=True, null=True)),
                ('date_emission', models.DateField()),
                ('date_validite', models.DateField(blank=True, null=True)),
                ('conditions_paiement', models.TextField(blank=True, null=True)),
                ('delai_livraison', models.CharField(blank=True, max_length=100, null=True)),
                ('port_chargement', models.CharField(blank=True, default='Douala, Cameroun', max_length=100, null=True)),
                ('certifications', models.CharField(blank=True, help_text='Ex: GLOBALG.A.P., Bio, etc.', max_length=255, null=True)),
                ('conditions_emballage', models.TextField(blank=True, help_text='Ex: Cartons de 4kg, vrac, etc.', null=True)),
                ('incoterm', models.CharField(choices=[('EXW', 'EXW - Ex Works'), ('FCA', 'FCA - Free Carrier'), ('FAS', 'FAS - Free Alongside Ship'), ('FOB', 'FOB - Free On Board'), ('CFR', 'CFR - Cost and Freight'), ('CIF', 'CIF - Cost, Insurance and Freight'), ('CPT', 'CPT - Carriage Paid To'), ('CIP', 'CIP - Carriage and Insurance Paid To'), ('DAP', 'DAP - Delivered At Place'), ('DPU', 'DPU - Delivered at Place Unloaded'), ('DDP', 'DDP - Delivered Duty Paid')], default='FOB', max_length=10)),
                ('frais_inspection', models.DecimalField(decimal_places=2, default=0, help_text='SGS, Phytosanitaire...', max_digits=12)),
                ('frais_logistique', models.DecimalField(decimal_places=2, default=0, help_text='Fret, Assurance...', max_digits=12)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tva_pourcentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('devise', models.CharField(choices=[('FCFA', 'Franc CFA'), ('EUR', 'Euro'), ('USD', 'Dollar US')], default='FCFA', max_length=10)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé'), ('EXPIRE', 'Expiré')], default='BROUILLON', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('creee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='devis_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_generees', to='supplychain.devis'),
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unite', models.CharField(default='kg', max_length=20)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sous_total', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='supplychain.devis')),
            ],
        ),
    ]
