# Generated by Django 6.0.1 on 2026-03-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistiq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_fr', models.CharField(max_length=150)),
                ('label_en', models.CharField(blank=True, max_length=150, null=True)),
                ('valeur', models.PositiveIntegerField()),
                ('suffixe', models.CharField(default='+', help_text='Ex: +, %, K', max_length=10)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('est_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
