# Generated by Django 6.0.1 on 2026-03-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_fr', models.CharField(max_length=255)),
                ('titre_en', models.CharField(blank=True, max_length=255, null=True)),
                ('extrait_fr', models.TextField()),
                ('extrait_en', models.TextField(blank=True, null=True)),
                ('contenu_fr', models.TextField()),
                ('contenu_en', models.TextField(blank=True, null=True)),
                ('auteur', models.CharField(default='Admin', max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('date_publication', models.DateField()),
                ('est_publie', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Article de blog',
                'verbose_name_plural': 'Articles de blog',
                'ordering': ['ordre', '-date_publication', '-id'],
            },
        ),
    ]
