# Generated by Django 6.0.1 on 2026-03-26 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnonceInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('priorite', models.CharField(choices=[('NORMALE', 'Normale'), ('IMPORTANTE', 'Importante'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=15)),
                ('destinataires', models.CharField(choices=[('TOUS', 'Tous les employés'), ('ADMIN', 'Administrateurs'), ('DIR', 'Direction'), ('RH', 'Ressources Humaines'), ('COMPTA', 'Comptabilité'), ('COMM', 'Commerciaux'), ('LOG', 'Logistique'), ('AGRI', 'Agents terrain')], default='TOUS', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='administration/annonces/')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='administration/annonces/pj/')),
                ('est_active', models.BooleanField(default=True)),
                ('est_epinglee', models.BooleanField(default=False)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('publiee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_publiees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annonce interne',
                'verbose_name_plural': 'Annonces internes',
                'ordering': ['-est_epinglee', '-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='ParametreGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('valeur', models.TextField()),
                ('type_valeur', models.CharField(choices=[('TEXTE', 'Texte'), ('NOMBRE', 'Nombre'), ('BOOLEEN', 'Booléen'), ('EMAIL', 'Email'), ('URL', 'URL'), ('JSON', 'JSON')], default='TEXTE', max_length=10)),
                ('categorie', models.CharField(choices=[('GENERAL', 'Général'), ('ENTREPRISE', 'Informations entreprise'), ('FINANCE', 'Finance'), ('RH', 'Ressources Humaines'), ('MARKETING', 'Marketing'), ('NOTIFICATIONS', 'Notifications'), ('SECURITE', 'Sécurité'), ('SYSTEME', 'Système')], default='GENERAL', max_length=20)),
                ('label', models.CharField(help_text='Nom lisible du paramètre', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('est_modifiable', models.BooleanField(default=True)),
                ('est_visible', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametres_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètre global',
                'verbose_name_plural': 'Paramètres globaux',
                'ordering': ['categorie', 'cle'],
            },
        ),
        migrations.CreateModel(
            name='TacheInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('EN_ATTENTE', 'En attente'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='A_FAIRE', max_length=15)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('module_lie', models.CharField(blank=True, max_length=100, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('assignee_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_assignees', to=settings.AUTH_USER_MODEL)),
                ('creee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tâche interne',
                'verbose_name_plural': 'Tâches internes',
                'ordering': ['-priorite', 'date_echeance', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LogActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('CONSULTATION', 'Consultation'), ('EXPORT', 'Export de données'), ('IMPORT', 'Import de données'), ('APPROBATION', 'Approbation'), ('REJET', 'Rejet'), ('ERREUR', 'Erreur système'), ('AUTRE', 'Autre')], max_length=20)),
                ('module', models.CharField(choices=[('PRODUITS', 'Produits'), ('SUPPLYCHAIN', 'Supply Chain'), ('FINANCE', 'Finance'), ('RH', 'Ressources Humaines'), ('MARKETING', 'Marketing'), ('CONTENT', 'Contenu'), ('GALLERY', 'Galerie'), ('PARTNERS', 'Partenaires'), ('BLOG', 'Blog'), ('STATISTICS', 'Statistiques'), ('TESTIMONIALS', 'Témoignages'), ('ACCOUNTS', 'Comptes utilisateurs'), ('ADMINISTRATION', 'Administration'), ('AUTH', 'Authentification'), ('SYSTEME', 'Système')], max_length=20)),
                ('severite', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur'), ('CRITICAL', 'Critique')], default='INFO', max_length=10)),
                ('description', models.TextField()),
                ('objet_type', models.CharField(blank=True, help_text="Type d'objet concerné (ex: Facture, Commande)", max_length=100, null=True)),
                ('objet_id', models.PositiveIntegerField(blank=True, help_text="ID de l'objet concerné", null=True)),
                ('objet_representation', models.CharField(blank=True, help_text="Représentation textuelle de l'objet", max_length=255, null=True)),
                ('donnees_avant', models.JSONField(blank=True, help_text='État avant modification', null=True)),
                ('donnees_apres', models.JSONField(blank=True, help_text='État après modification', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_activite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'activité",
                'verbose_name_plural': "Logs d'activité",
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['-date_action'], name='administrat_date_ac_f264c8_idx'), models.Index(fields=['utilisateur', '-date_action'], name='administrat_utilisa_04c75e_idx'), models.Index(fields=['module', '-date_action'], name='administrat_module_06de9d_idx'), models.Index(fields=['action', '-date_action'], name='administrat_action_dbfd9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Succès'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur'), ('TACHE', 'Tâche à faire')], default='INFO', max_length=10)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10)),
                ('lien_module', models.CharField(blank=True, max_length=100, null=True)),
                ('lien_objet_id', models.PositiveIntegerField(blank=True, null=True)),
                ('lien_url', models.CharField(blank=True, help_text='URL vers la ressource', max_length=500, null=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_envoyees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['destinataire', '-date_creation'], name='administrat_destina_e1f98b_idx'), models.Index(fields=['destinataire', 'est_lue'], name='administrat_destina_f5ebb5_idx')],
            },
        ),
    ]
