# Generated by Django 6.0.1 on 2026-04-16 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression')], max_length=15)),
                ('module', models.CharField(help_text='App/Modèle concerné', max_length=100)),
                ('objet_type', models.CharField(help_text="Type de l'objet modifié", max_length=100)),
                ('objet_id', models.PositiveIntegerField(help_text="ID de l'objet modifié")),
                ('objet_representation', models.CharField(blank=True, max_length=500, null=True)),
                ('champs_modifies', models.JSONField(blank=True, help_text='Liste des champs modifiés avec anciennes et nouvelles valeurs', null=True)),
                ('resume', models.TextField(blank=True, help_text='Résumé lisible de la modification', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_effectuees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de modification',
                'verbose_name_plural': 'Historique des modifications',
                'ordering': ['-date_modification'],
                'indexes': [models.Index(fields=['-date_modification'], name='administrat_date_mo_19e0f8_idx'), models.Index(fields=['objet_type', 'objet_id'], name='administrat_objet_t_25b8e2_idx'), models.Index(fields=['utilisateur', '-date_modification'], name='administrat_utilisa_ce5e75_idx')],
            },
        ),
    ]
