# Generated by Django 6.0.1 on 2026-05-03 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_historiquemodification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentementRGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Pour les visiteurs non connectés', max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('type_consentement', models.CharField(choices=[('COOKIES', 'Cookies'), ('NEWSLETTER', 'Newsletter'), ('DONNEES_PERSONNELLES', 'Traitement données personnelles'), ('MARKETING', 'Communications marketing'), ('ANALYTICS', 'Statistiques et analytics'), ('TIERS', 'Partage avec des tiers')], max_length=25)),
                ('accepte', models.BooleanField(default=False)),
                ('version_politique', models.CharField(default='1.0', max_length=20)),
                ('date_consentement', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_retrait', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consentements_rgpd', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consentement RGPD',
                'verbose_name_plural': 'Consentements RGPD',
                'ordering': ['-date_consentement'],
            },
        ),
        migrations.CreateModel(
            name='DemandeRGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demandeur_nom', models.CharField(max_length=255)),
                ('demandeur_email', models.EmailField(max_length=254)),
                ('type_demande', models.CharField(choices=[('ACCES', "Droit d'accès"), ('RECTIFICATION', 'Droit de rectification'), ('SUPPRESSION', "Droit à l'effacement"), ('PORTABILITE', 'Droit à la portabilité'), ('OPPOSITION', "Droit d'opposition"), ('LIMITATION', 'Droit à la limitation')], max_length=15)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de traitement'), ('EN_COURS', 'En cours de traitement'), ('TRAITE', 'Traité'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=15)),
                ('reponse', models.TextField(blank=True, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('date_limite', models.DateField(blank=True, help_text='30 jours max selon RGPD', null=True)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_rgpd_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande RGPD',
                'verbose_name_plural': 'Demandes RGPD',
                'ordering': ['-date_demande'],
            },
        ),
    ]
