# Generated by Django 6.0.1 on 2026-03-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo du partenaire', null=True, upload_to='partners/')),
                ('type_partenaire', models.CharField(choices=[('FOURNISSEUR', 'Fournisseur'), ('CLIENT_B2B', 'Client B2B'), ('DISTRIBUTEUR', 'Distributeur'), ('INVESTISSEUR', 'Investisseur'), ('INSTITUTION', 'Institution'), ('ONG', 'ONG / Association'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('site_web', models.URLField(blank=True, help_text='Site web du partenaire (optionnel)', null=True)),
                ('pays', models.CharField(blank=True, help_text='Pays du partenaire', max_length=100, null=True)),
                ('est_visible', models.BooleanField(default=True, help_text='Afficher ce partenaire sur le site public')),
                ('est_featured', models.BooleanField(default=False, help_text='Mettre en avant ce partenaire (badge spécial)')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier)")),
                ('date_debut_partenariat', models.DateField(blank=True, help_text='Date de début du partenariat', null=True)),
            ],
        ),
    ]
