# Generated by Django 6.0.1 on 2026-04-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partenaire',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': 'Partenaire', 'verbose_name_plural': 'Partenaires'},
        ),
        migrations.AddField(
            model_name='partenaire',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email du contact', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='contact_nom',
            field=models.CharField(blank=True, help_text='Nom du contact de référence', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='contact_telephone',
            field=models.CharField(blank=True, help_text='Téléphone du contact', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='ville',
            field=models.CharField(blank=True, help_text='Ville du partenaire', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='est_featured',
            field=models.BooleanField(default=False, help_text='Mettre en avant'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='est_visible',
            field=models.BooleanField(default=True, help_text='Afficher sur le site public'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='ordre',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='pays',
            field=models.CharField(blank=True, default='Cameroun', help_text='Pays du partenaire', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='site_web',
            field=models.URLField(blank=True, help_text='Site web du partenaire', null=True),
        ),
    ]
