# Generated by Django 6.0.1 on 2026-01-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du produit')),
                ('type_produit', models.CharField(choices=[('ANANAS', 'Ananas'), ('PAPAYE', 'Papaye'), ('COCO', 'Noix de Coco'), ('COROSSOL', 'Corossol'), ('LEGUME', 'Légume'), ('TUBERCULE', 'Tubercule'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('description_fr', models.TextField(verbose_name='Description (FR)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (EN)')),
                ('prix_unitaire_fcfa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('stock_kg', models.IntegerField(default=0, verbose_name='Stock actuel (KG)')),
                ('est_premium', models.BooleanField(default=False, verbose_name='Produit Premium?')),
            ],
            options={
                'verbose_name': 'Produit Agricole',
                'verbose_name_plural': 'Produits Agricoles',
            },
        ),
    ]
