# Generated by Django 6.0.1 on 2026-01-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produitagricole',
            options={},
        ),
    ]
