# Generated by Django 6.0.1 on 2026-02-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_alter_produitagricole_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitagricole',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AlterField(
            model_name='produitagricole',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produitagricole',
            name='description_fr',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='produitagricole',
            name='est_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produitagricole',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produitagricole',
            name='prix_unitaire_fcfa',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produitagricole',
            name='stock_kg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produitagricole',
            name='type_produit',
            field=models.CharField(choices=[('ANANAS', 'Ananas'), ('DESHYDRATE', 'Deshydrate'), ('EPICES', 'Epices'), ('FRUITS', 'Fruits'), ('LEGUME', 'Légume'), ('TUBERCULE', 'Tubercule'), ('AUTRE', 'Autre')], max_length=20),
        ),
    ]
