# Generated by Django 6.0.5 on 2026-05-17 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_produitagricole_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitagricole',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
