# Generated by Django 6.0.1 on 2026-03-25 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_diriges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(editable=False, max_length=20, unique=True)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], default='M', max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=150, null=True)),
                ('nationalite', models.CharField(default='Camerounaise', max_length=100)),
                ('poste', models.CharField(max_length=200)),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI - Contrat à Durée Indéterminée'), ('CDD', 'CDD - Contrat à Durée Déterminée'), ('STAGE', 'Stage'), ('FREELANCE', 'Freelance'), ('INTERIM', 'Intérimaire')], default='CDI', max_length=15)),
                ('date_embauche', models.DateField()),
                ('date_fin_contrat', models.DateField(blank=True, null=True)),
                ('salaire_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('telephone_personnel', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_urgence_telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rh/photos/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='rh/cv/')),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='rh.departement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_employe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('ANNUEL', 'Congé annuel'), ('MALADIE', 'Congé maladie'), ('MATERNITE', 'Congé maternité'), ('PATERNITE', 'Congé paternité'), ('SANS_SOLDE', 'Congé sans solde'), ('EXCEPTIONNEL', 'Congé exceptionnel'), ('FORMATION', 'Congé de formation')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_jours', models.PositiveIntegerField()),
                ('motif', models.TextField()),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='rh/conges/')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=15)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('commentaire_decision', models.TextField(blank=True, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_approuves', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_conges', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congés',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='ContratTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('FREELANCE', 'Freelance'), ('AVENANT', 'Avenant')], max_length=15)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avantages', models.TextField(blank=True, help_text='Prime transport, logement, etc.', null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='rh/contrats/')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('RESILIE', 'Résilié'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Contrat de travail',
                'verbose_name_plural': 'Contrats de travail',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='FichePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('mois', models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')])),
                ('annee', models.PositiveIntegerField()),
                ('salaire_brut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prime_transport', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prime_logement', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prime_risque', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('autres_primes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('heures_supplementaires', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cotisation_cnps', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impot_irpp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('autres_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salaire_net', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('PAYEE', 'Payée')], default='BROUILLON', max_length=15)),
                ('document', models.FileField(blank=True, null=True, upload_to='rh/fiches_paie/')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('payee_le', models.DateField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_paie', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Fiche de paie',
                'verbose_name_plural': 'Fiches de paie',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('employe', 'mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'Retard'), ('CONGE', 'En congé'), ('MISSION', 'En mission'), ('MALADIE', 'Maladie')], default='PRESENT', max_length=15)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date', 'employe'],
                'unique_together': {('employe', 'date')},
            },
        ),
    ]
