# Generated by Django 6.0.1 on 2026-04-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='email_personnel',
            field=models.EmailField(blank=True, help_text="Email personnel de l'employé", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='niveau_etude',
            field=models.CharField(blank=True, choices=[('SANS_DIPLOME', 'Sans diplôme'), ('CEP', 'CEP / FSLC'), ('BEPC', 'BEPC / GCE O-Level'), ('PROBATOIRE', 'Probatoire'), ('BAC', 'Baccalauréat / GCE A-Level'), ('BTS', 'BTS / HND'), ('LICENCE', 'Licence / Bachelor'), ('MASTER', 'Master'), ('DOCTORAT', 'Doctorat / PhD'), ('AUTRE', 'Autre')], help_text="Niveau d'étude de l'employé", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='nom_complet',
            field=models.CharField(blank=True, help_text="Nom complet de l'employé (si différent du compte utilisateur)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='pays_residence',
            field=models.CharField(blank=True, default='Cameroun', help_text='Pays de résidence', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='statut_marital',
            field=models.CharField(blank=True, choices=[('CELIBATAIRE', 'Célibataire'), ('MARIE', 'Marié(e)'), ('DIVORCE', 'Divorcé(e)'), ('VEUF', 'Veuf/Veuve'), ('UNION_LIBRE', 'Union libre')], help_text="Statut marital de l'employé", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='ville',
            field=models.CharField(blank=True, help_text='Ville de résidence', max_length=100, null=True),
        ),
    ]
