# Generated by Django 6.0.5 on 2026-05-17 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_employe_email_personnel_employe_niveau_etude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='rh/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
