# Generated by Django 6.0.1 on 2026-02-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=255)),
                ('nom_contact', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=50)),
                ('produits', models.TextField(help_text='Liste de produits demandés (JSON ou texte)')),
                ('quantite_tonnes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequence', models.CharField(choices=[('unique', 'Commande unique'), ('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('annuelle', 'Annuelle')], max_length=20)),
                ('destination', models.CharField(max_length=255)),
                ('exigences', models.TextField(blank=True, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
            ],
        ),
    ]
