# Generated by Django 6.0.1 on 2026-03-26 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('produits', '0003_produitagricole_image_and_more'),
        ('supplychain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDépense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='demandedevis',
            options={'ordering': ['-date_demande'], 'verbose_name': 'Demande de devis', 'verbose_name_plural': 'Demandes de devis'},
        ),
        migrations.CreateModel(
            name='BudgetMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')])),
                ('annee', models.PositiveIntegerField()),
                ('budget_prevu_revenus', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('budget_prevu_depenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('revenus_reels', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('depenses_reelles', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ecart_revenus', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('ecart_depenses', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('solde_net', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('est_cloture', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget mensuel',
                'verbose_name_plural': 'Budgets mensuels',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='DepenseOperationnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('description', models.TextField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('date_depense', models.DateField()),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='finance/depenses/')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', "En attente d'approbation"), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('PAYEE', 'Payée')], default='EN_ATTENTE', max_length=15)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_approuvees', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='finance.categoriedépense')),
                ('soumis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_soumises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépense opérationnelle',
                'verbose_name_plural': 'Dépenses opérationnelles',
                'ordering': ['-date_depense'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=50, unique=True)),
                ('client_nom', models.CharField(max_length=255)),
                ('client_entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('client_adresse', models.TextField(blank=True, null=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tva_pourcentage', models.DecimalField(decimal_places=2, default=19.25, max_digits=5)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('solde_restant', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('devise', models.CharField(choices=[('FCFA', 'Franc CFA'), ('EUR', 'Euro'), ('USD', 'Dollar US'), ('GBP', 'Livre Sterling')], default='FCFA', max_length=10)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYEE', 'Envoyée'), ('PAYEE', 'Payée'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('EN_RETARD', 'En retard'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=25)),
                ('date_emission', models.DateField()),
                ('date_echeance', models.DateField()),
                ('conditions_paiement', models.TextField(blank=True, default='Paiement à réception de facture. Pénalité de retard : 1.5% par mois.', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='finance/factures/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='supplychain.commandeclient')),
                ('creee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unite', models.CharField(default='kg', max_length=20)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='finance.facture')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_factures', to='produits.produitagricole')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mode_paiement', models.CharField(choices=[('VIREMENT', 'Virement bancaire'), ('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Chèque'), ('CARTE', 'Carte bancaire'), ('PAYPAL', 'PayPal'), ('AUTRE', 'Autre')], default='VIREMENT', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de confirmation'), ('CONFIRME', 'Confirmé'), ('ECHOUE', 'Échoué'), ('REMBOURSE', 'Remboursé')], default='EN_ATTENTE', max_length=15)),
                ('reference_externe', models.CharField(blank=True, help_text='Numéro de transaction, référence bancaire, etc.', max_length=100, null=True)),
                ('preuve', models.FileField(blank=True, null=True, upload_to='finance/paiements/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_paiement', models.DateField()),
                ('date_confirmation', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('confirme_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_confirmes', to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='finance.facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
