# Generated by Django 6.0.1 on 2026-03-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_categoriedépense_alter_demandedevis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='devise',
            field=models.CharField(choices=[('FCFA', 'Franc CFA'), ('EUR', 'Euro'), ('USD', 'Dollar US'), ('GBP', 'Livre Sterling'), ('CNY', 'Yuan Chinois'), ('NGN', 'Naira nigérian')], default='FCFA', max_length=10),
        ),
    ]
