# Generated by Django 6.0.1 on 2026-04-08 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_facture_devise'),
        ('location', '0001_initial'),
        ('supplychain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='commande_source',
            field=models.ForeignKey(blank=True, help_text="Commande client à l'origine de cette facture", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_generees', to='supplychain.commandeclient'),
        ),
        migrations.AddField(
            model_name='facture',
            name='contrat_location_source',
            field=models.ForeignKey(blank=True, help_text="Contrat de location à l'origine de cette facture", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_generees', to='location.contratlocation'),
        ),
        migrations.AddField(
            model_name='facture',
            name='est_auto_generee',
            field=models.BooleanField(default=False, help_text='Facture générée automatiquement par synchronisation'),
        ),
        migrations.AddField(
            model_name='facture',
            name='type_operation',
            field=models.CharField(choices=[('ACHAT', 'Vente de produits (Achat client)'), ('LOCATION', 'Location de matériel'), ('SERVICE', 'Prestation de service'), ('AUTRE', 'Autre')], default='ACHAT', help_text="Type d'opération facturée", max_length=15),
        ),
    ]
