# Generated by Django 6.0.1 on 2026-04-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_facture_commande_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='type_operation',
            field=models.CharField(choices=[('ACHAT', 'Vente de produits agricoles (Achat client)'), ('ACHAT', 'Vente de matériel (Achat client)'), ('LOCATION', 'Location de matériel'), ('SERVICE', 'Prestation de service'), ('AUTRE', 'Autre')], default='ACHAT', help_text="Type d'opération facturée", max_length=15),
        ),
    ]
