# Generated by Django 6.0.1 on 2026-04-13 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0002_reglealerteiot_capteuriot_donneestelemetrie_and_more'),
        ('finance', '0005_alter_facture_type_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignefacture',
            name='categorie_ligne',
            field=models.CharField(choices=[('PRODUIT_AGRICOLE', 'Produit agricole'), ('MATERIEL', 'Matériel / Équipement'), ('LOCATION', 'Location de matériel'), ('SERVICE', 'Prestation de service'), ('TRANSPORT', 'Transport / Livraison'), ('PENALITE', 'Pénalité'), ('AUTRE', 'Autre')], default='PRODUIT_AGRICOLE', help_text='Catégorie de la ligne pour le bilan', max_length=20),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='equipement',
            field=models.ForeignKey(blank=True, help_text='Équipement concerné (si location/vente matériel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_factures', to='equipements.equipement'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
