"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charger les variables du fichier .env à la racine du dépôt
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'clé-temporaire-dev-uniquement')
### SECRET_KEY = 'django-insecure-6u1y*4&fu*0za+487cu2eeoky@odlu4ub67rlja!-8int(cq97' ###

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

# Dans INSTALLED_APPS
INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Librairies tierces
    'rest_framework',
    
    # NOS MICROSERVICES
    'produits',
    'users',
    'rh',
    'finance',
    'supplychain',
    'content',
    'authentication',
    'partners',
    'gallery',
    'marketing',
    'administration',
    'accounts',
    'statistiq',
    'blog',
    'testimonials',
    'equipements',
    'location',
    'drf_spectacular',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
]

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

if os.environ.get('DB_NAME'):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD':  os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '3306'),
    }




# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Assurez-vous que ce dossier existe maintenant
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Ajoutez ceci à la fin
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuration pour l'API (Sécurité initiale)
#CORS_ALLOW_ALL_ORIGINS = True # À retirer en production, mais utile pour tester le frontend localement


# CORS_ALLOW_ALL_ORIGINS = False
# CORS_ALLOWED_ORIGINS = [
#    'https://kamcofarm.com',
#    'https://dashboard.kamcofarm.com',
# ]
# if DEBUG:
#    CORS_ALLOWED_ORIGINS += ['http://127.0.0.1:5500', 'http://localhost:5500'] 


# CORS
CORS_ALLOW_ALL_ORIGINS = DEBUG
if not DEBUG:
    CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ORIGINS', '').split(',')

# URLs
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://127.0.0.1:5500')
BACKEND_URL = os.environ.get('BACKEND_URL', 'http://127.0.0.1:8000')



CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'GET',
    'OPTIONS',
    'HEAD',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
]

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
     'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',
        'user': '100/minute',
        'login': '5/minute',
    },
}


FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 Mo max
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024


# ========================================
# CONFIGURATION EMAIL
# ========================================

# Pour le développement (affiche les emails dans la console)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Pour la production avec Gmail (décommenter et configurer)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'votre.email@gmail.com'
# EMAIL_HOST_PASSWORD = 'votre_mot_de_passe_application'

# Pour la production avec un autre SMTP
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.fossagrofarm.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'noreply@fossagrofarm.com'
# EMAIL_HOST_PASSWORD = 'mot_de_passe_smtp'

DEFAULT_FROM_EMAIL = 'FOSS AGRO FARM <noreply@fossagrofarm.com>'
ADMIN_EMAIL = 'infoclients@fossagrofarm.com'
CONTACT_EMAIL = 'infoclients@fossagrofarm.com'

# URL du frontend (pour les liens dans les emails)
FRONTEND_URL = 'http://127.0.0.1:5500'
BACKEND_URL = 'http://127.0.0.1:8000'



CSRF_TRUSTED_ORIGINS = [
    'https://kamcofarm.com',
    'https://dashboard.kamcofarm.com',
]


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# ========================================
# DOCUMENTATION API — DRF SPECTACULAR
# ========================================
SPECTACULAR_SETTINGS = {
    'TITLE': 'KAMCO FARM — API Documentation',
    'DESCRIPTION': (
        '# 🌱 API KAMCO FARM / \n'
        'Documentation complète de l\'API REST pour la plateforme de gestion agricole KAMCO FARM.\n\n'
        '## 🔐 Authentification\n\n'
        'L\'API utilise **JWT (JSON Web Token)** pour l\'authentification.\n\n'
        '### Obtenir un token\n'
        '```\n'
        'POST /api/auth/token/\n'
        '{"username": "votre_username", "password": "votre_password"}\n'
        '```\n\n'
        '### Utiliser le token\n'
        '```\n'
        'Authorization: Bearer <votre_access_token>\n'
        '```\n\n'
        '## 📦 Modules disponibles\n\n'
        '| Module | Préfixe | Description |\n'
        '|--------|---------|-------------|\n'
        '| 🍍 Produits | /api/produits/ | Produits agricoles |\n'
        '| 🖼 Galerie | /api/gallery/ | Galerie photos |\n'
        '| 🤝 Partenaires | /api/partners/ | Partenaires |\n'
        '| 📰 Blog | /api/blog/ | Articles de blog |\n'
        '| 💬 Témoignages | /api/testimonials/ | Témoignages clients |\n'
        '| 📊 Statistiques | /api/statistiq/ | Statistiques du site |\n'
        '| 🚚 Supply Chain | /api/supplychain/ | Commandes, fournisseurs, livraisons |\n'
        '| 💰 Finance | /api/finance/ | Factures, paiements, dépenses |\n'
        '| 👥 RH | /api/rh/ | Employés, congés, paie |\n'
        '| 📣 Marketing | /api/marketing/ | Leads, campagnes, SAV |\n'
        '| 🚜 Équipements | /api/equipements/ | Flotte, maintenance, IoT |\n'
        '| 📋 Location | /api/location/ | Réservations, contrats |\n'
        '| ⚙ Administration | /api/administration/ | Logs, notifications |\n'
        '| 👤 Comptes | /api/accounts/ | Utilisateurs |\n\n'

        ## 👥 Rôles et permissions

        '| Rôle | Code | Accès |'
        '|------|------|-------|'
        '| Administrateur | ADMIN | Tout |'
        '| Directeur | DIR | Tout |'
        '| RH | RH | Module RH |'
        '| Comptable | COMPTA | Module Finance |'
        '| Commercial | COMM | Supply Chain, Marketing, Location |'
        '| Logistique | LOG | Supply Chain, Équipements, Location |'
        '| Agent terrain | AGRI | Limité |'
        '| Visiteur | VISITOR | Lecture seule publique |'

        '## 📞 Contact\n\n'
        '- Email : infoclients@kamcofarm.com\n'
        '- Téléphone : +237 6 94 57 20 50\n'
        '- Adresse : AWAE - Yaoundé, Cameroun\n'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [
        {'name': 'Auth', 'description': 'Authentification JWT'},
        {'name': 'Accounts', 'description': 'Gestion des comptes utilisateurs'},
        {'name': 'Produits', 'description': 'Produits agricoles'},
        {'name': 'Gallery', 'description': 'Galerie photos'},
        {'name': 'Partners', 'description': 'Partenaires'},
        {'name': 'Blog', 'description': 'Articles de blog'},
        {'name': 'Testimonials', 'description': 'Témoignages clients'},
        {'name': 'Statistics', 'description': 'Statistiques du site'},
        {'name': 'Supply Chain', 'description': 'Commandes, fournisseurs, livraisons, stocks'},
        {'name': 'Finance', 'description': 'Factures, paiements, dépenses, budgets'},
        {'name': 'RH', 'description': 'Ressources humaines'},
        {'name': 'Marketing', 'description': 'Leads, campagnes, newsletter, SAV'},
        {'name': 'Equipements', 'description': 'Flotte, maintenance, IoT'},
        {'name': 'Location', 'description': 'Réservations, contrats, cautions'},
        {'name': 'Administration', 'description': 'Logs, notifications, tâches'},
    ],
    'CONTACT': {
        'name': 'KAMCO FARM - Support technique',
        'email': 'infoclients@kamcofarm.com',
        'url': 'https://kamcofarm.com',
    },
    'LICENSE': {
        'name': 'Propriétaire',
    },
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
        'filter': True,
        'docExpansion': 'none',
        'defaultModelsExpandDepth': 2,
        'defaultModelExpandDepth': 2,
    },
    'SWAGGER_UI_DIST': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest',
}