# Generated by Django 6.0.1 on 2026-03-30 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegleAlerteIoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_capteur', models.CharField(choices=[('TEMPERATURE', 'Température'), ('PRESSION', 'Pression'), ('VIBRATION', 'Vibration'), ('GPS', 'Géolocalisation GPS'), ('HEURES_MOTEUR', 'Compteur heures moteur'), ('CARBURANT', 'Niveau carburant'), ('VITESSE', 'Vitesse'), ('HUMIDITE', 'Humidité'), ('REGIME_MOTEUR', 'Régime moteur (RPM)'), ('BATTERIE', 'Niveau batterie'), ('DIAGNOSTIC', 'Diagnostic moteur (OBD)'), ('AUTRE', 'Autre')], max_length=20)),
                ('condition', models.CharField(choices=[('SUP', 'Supérieur à'), ('INF', 'Inférieur à'), ('EGAL', 'Égal à'), ('ENTRE', 'Entre deux valeurs'), ('HORS', 'Hors plage'), ('VARIATION', 'Variation brusque'), ('INACTIVITE', 'Inactivité capteur')], max_length=15)),
                ('valeur_seuil', models.DecimalField(decimal_places=4, max_digits=12)),
                ('valeur_seuil_max', models.DecimalField(blank=True, decimal_places=4, help_text='Pour condition ENTRE ou HORS', max_digits=12, null=True)),
                ('pourcentage_variation', models.DecimalField(blank=True, decimal_places=2, help_text='Pour condition VARIATION (ex: 20 = 20%)', max_digits=5, null=True)),
                ('duree_inactivite_minutes', models.PositiveIntegerField(blank=True, help_text='Pour condition INACTIVITE', null=True)),
                ('severite', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('DANGER', 'Danger'), ('CRITIQUE', 'Critique')], default='WARNING', max_length=10)),
                ('action', models.CharField(choices=[('NOTIFICATION', 'Notification uniquement'), ('INTERVENTION', 'Créer intervention automatique'), ('ARRET', 'Notification + intervention urgente'), ('EMAIL', 'Notification + email')], default='NOTIFICATION', max_length=15)),
                ('est_active', models.BooleanField(default=True)),
                ('cooldown_minutes', models.PositiveIntegerField(default=30, help_text='Minutes minimum entre deux alertes du même type')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Règle d'alerte IoT",
                'verbose_name_plural': "Règles d'alerte IoT",
                'ordering': ['type_capteur', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CapteurIoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(help_text='ID unique du capteur', max_length=100, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('type_capteur', models.CharField(choices=[('TEMPERATURE', 'Température'), ('PRESSION', 'Pression'), ('VIBRATION', 'Vibration'), ('GPS', 'Géolocalisation GPS'), ('HEURES_MOTEUR', 'Compteur heures moteur'), ('CARBURANT', 'Niveau carburant'), ('VITESSE', 'Vitesse'), ('HUMIDITE', 'Humidité'), ('REGIME_MOTEUR', 'Régime moteur (RPM)'), ('BATTERIE', 'Niveau batterie'), ('DIAGNOSTIC', 'Diagnostic moteur (OBD)'), ('AUTRE', 'Autre')], max_length=20)),
                ('unite_mesure', models.CharField(blank=True, help_text='Ex: °C, bar, km/h, RPM', max_length=30, null=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('DEFAILLANT', 'Défaillant'), ('DECONNECTE', 'Déconnecté')], default='ACTIF', max_length=15)),
                ('seuil_min', models.DecimalField(blank=True, decimal_places=2, help_text='Valeur minimum avant alerte', max_digits=10, null=True)),
                ('seuil_max', models.DecimalField(blank=True, decimal_places=2, help_text='Valeur maximum avant alerte', max_digits=10, null=True)),
                ('seuil_critique_min', models.DecimalField(blank=True, decimal_places=2, help_text='Valeur minimum critique (arrêt immédiat)', max_digits=10, null=True)),
                ('seuil_critique_max', models.DecimalField(blank=True, decimal_places=2, help_text='Valeur maximum critique (arrêt immédiat)', max_digits=10, null=True)),
                ('derniere_valeur', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('derniere_lecture', models.DateTimeField(blank=True, null=True)),
                ('frequence_lecture_secondes', models.PositiveIntegerField(default=300, help_text="Fréquence d'envoi en secondes")),
                ('est_actif', models.BooleanField(default=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50, null=True)),
                ('date_installation', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capteurs', to='equipements.equipement')),
            ],
            options={
                'verbose_name': 'Capteur IoT',
                'verbose_name_plural': 'Capteurs IoT',
                'ordering': ['equipement', 'type_capteur'],
            },
        ),
        migrations.CreateModel(
            name='DonneesTelemetrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unite', models.CharField(blank=True, max_length=30, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Données brutes supplémentaires du capteur', null=True)),
                ('est_anomalie', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnees', to='equipements.capteuriot')),
            ],
            options={
                'verbose_name': 'Donnée télémétrie',
                'verbose_name_plural': 'Données télémétrie',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlerteIoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severite', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('DANGER', 'Danger'), ('CRITIQUE', 'Critique')], max_length=10)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('ACQUITTEE', 'Acquittée'), ('RESOLUE', 'Résolue'), ('IGNOREE', 'Ignorée')], default='ACTIVE', max_length=15)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('valeur_declenchement', models.DecimalField(decimal_places=4, max_digits=12)),
                ('seuil_depasse', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('date_acquittement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_resolution', models.TextField(blank=True, null=True)),
                ('date_alerte', models.DateTimeField(auto_now_add=True)),
                ('acquittee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_acquittees', to=settings.AUTH_USER_MODEL)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_iot', to='equipements.equipement')),
                ('intervention_creee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_iot_source', to='equipements.interventionmaintenance')),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='equipements.capteuriot')),
                ('donnee_telemetrie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='equipements.donneestelemetrie')),
            ],
            options={
                'verbose_name': 'Alerte IoT',
                'verbose_name_plural': 'Alertes IoT',
                'ordering': ['-date_alerte'],
            },
        ),
        migrations.AddIndex(
            model_name='donneestelemetrie',
            index=models.Index(fields=['capteur', '-timestamp'], name='equipements_capteur_73585c_idx'),
        ),
        migrations.AddIndex(
            model_name='donneestelemetrie',
            index=models.Index(fields=['-timestamp'], name='equipements_timesta_473ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='donneestelemetrie',
            index=models.Index(fields=['est_anomalie', '-timestamp'], name='equipements_est_ano_aae83a_idx'),
        ),
        migrations.AddIndex(
            model_name='alerteiot',
            index=models.Index(fields=['statut', '-date_alerte'], name='equipements_statut_171e56_idx'),
        ),
        migrations.AddIndex(
            model_name='alerteiot',
            index=models.Index(fields=['equipement', '-date_alerte'], name='equipements_equipem_7bce94_idx'),
        ),
        migrations.AddIndex(
            model_name='alerteiot',
            index=models.Index(fields=['severite', '-date_alerte'], name='equipements_severit_d41632_idx'),
        ),
    ]
