# Generated by Django 6.0.1 on 2026-02-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('DIR', 'Directeur Général'), ('RH', 'Ressources Humaines'), ('COMPTA', 'Comptable'), ('COMM', 'Commercial'), ('LOG', 'Logistique'), ('AGRI', 'Agent terrain'), ('VISITOR', 'Visiteur')], default='VISITOR', max_length=10),
        ),
    ]
