# Generated by Django 5.2.16 on 2026-08-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_seed_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(help_text='Code interne (ex: ADMIN, DIR). Doit correspondre au champ User.role.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='couleur',
            field=models.CharField(default='#188701', help_text='Couleur du badge (hex).', max_length=20),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=list, help_text="Liste des capacités accordées (ex: ['finance', 'rh'])."),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='VISITOR', max_length=10),
        ),
    ]
