# Generated by Django 6.0.1 on 2026-03-26 20:20

import content.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieContenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icone', models.CharField(blank=True, help_text="Emoji ou classe d'icône", max_length=50, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie de contenu',
                'verbose_name_plural': 'Catégories de contenu',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='DocumentInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_document', models.CharField(choices=[('PROCEDURE', 'Procédure'), ('FORMULAIRE', 'Formulaire'), ('RAPPORT', 'Rapport'), ('CONTRAT_TYPE', 'Contrat type'), ('POLITIQUE', 'Politique interne'), ('FORMATION', 'Support de formation'), ('COMMUNICATION', 'Communication interne'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('visibilite', models.CharField(choices=[('TOUS', 'Tous les employés'), ('ADMIN_DIR', 'Administrateurs et Direction'), ('RH', 'Ressources Humaines'), ('FINANCE', 'Finance et Comptabilité'), ('LOGISTIQUE', 'Logistique'), ('COMMERCIAL', 'Commerciaux')], default='TOUS', max_length=20)),
                ('fichier', models.FileField(upload_to='content/documents_internes/')),
                ('taille_fichier', models.PositiveIntegerField(default=0, editable=False, help_text='Taille en octets')),
                ('extension', models.CharField(blank=True, editable=False, max_length=10)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('uploade_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document interne',
                'verbose_name_plural': 'Documents internes',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_fr', models.CharField(max_length=500)),
                ('question_en', models.CharField(blank=True, max_length=500, null=True)),
                ('reponse_fr', models.TextField()),
                ('reponse_en', models.TextField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('est_visible', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='content.categoriecontenu')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_media', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo'), ('AUDIO', 'Audio'), ('DOCUMENT', 'Document'), ('AUTRE', 'Autre')], default='IMAGE', max_length=15)),
                ('fichier', models.FileField(upload_to=content.models.media_upload_path)),
                ('miniature', models.ImageField(blank=True, null=True, upload_to='content/miniatures/')),
                ('taille_fichier', models.PositiveIntegerField(default=0, editable=False)),
                ('extension', models.CharField(blank=True, editable=False, max_length=10)),
                ('largeur', models.PositiveIntegerField(blank=True, help_text='Pour les images', null=True)),
                ('hauteur', models.PositiveIntegerField(blank=True, help_text='Pour les images', null=True)),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=255, null=True)),
                ('est_public', models.BooleanField(default=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('uploade_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias_uploades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fichier média',
                'verbose_name_plural': 'Fichiers médias',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='PageContenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_fr', models.CharField(max_length=255)),
                ('titre_en', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('contenu_fr', models.TextField()),
                ('contenu_en', models.TextField(blank=True, null=True)),
                ('extrait_fr', models.TextField(blank=True, help_text='Résumé court pour les listes', null=True)),
                ('extrait_en', models.TextField(blank=True, null=True)),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='content/pages/')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIEE', 'Publiée'), ('ARCHIVEE', 'Archivée')], default='BROUILLON', max_length=15)),
                ('est_mise_en_avant', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('meta_description_fr', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_description_en', models.CharField(blank=True, max_length=300, null=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_creees', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='content.categoriecontenu')),
            ],
            options={
                'verbose_name': 'Page de contenu',
                'verbose_name_plural': 'Pages de contenu',
                'ordering': ['ordre', '-date_publication', '-date_creation'],
            },
        ),
    ]
