# Generated by Django 6.0.1 on 2026-03-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=150)),
                ('fonction_client_fr', models.CharField(max_length=200)),
                ('fonction_client_en', models.CharField(blank=True, max_length=200, null=True)),
                ('entreprise', models.CharField(blank=True, max_length=200, null=True)),
                ('contenu_fr', models.TextField()),
                ('contenu_en', models.TextField(blank=True, null=True)),
                ('note', models.PositiveSmallIntegerField(default=5)),
                ('avatar_initiales', models.CharField(blank=True, max_length=5, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('est_visible', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['ordre', '-date_ajout'],
            },
        ),
    ]
